from tau2.utils.utils import DATA_DIR

AIRLINE_TIGHTER_POLICY_DATA_DIR = DATA_DIR / "tau2" / "domains" / "airline_tighter_policy"
AIRLINE_TIGHTER_POLICY_DB_PATH = AIRLINE_TIGHTER_POLICY_DATA_DIR / "db.json"
AIRLINE_TIGHTER_POLICY_POLICY_PATH = AIRLINE_TIGHTER_POLICY_DATA_DIR / "policy.md"
AIRLINE_TIGHTER_POLICY_TASK_SET_PATH = AIRLINE_TIGHTER_POLICY_DATA_DIR / "tasks.json"
