from tau2.utils.utils import DATA_DIR

AIRLINE_RELAXED_DATA_DIR = DATA_DIR / "tau2" / "domains" / "airline-relaxed"
AIRLINE_RELAXED_DB_PATH = AIRLINE_RELAXED_DATA_DIR / "db.json"
AIRLINE_RELAXED_POLICY_PATH = AIRLINE_RELAXED_DATA_DIR / "policy.md"
AIRLINE_RELAXED_TASK_SET_PATH = AIRLINE_RELAXED_DATA_DIR / "tasks.json"
